project:
  type: website
  output-dir: docs

website:
  title: "Mack White"
  favicon: images/fishy_logo.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd
      - Research.qmd
      - CV.qmd
      - Pics.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

