project:
  type: website
  output-dir: docs

website:
  title: "Mack White"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd
      - News.qmd
      - CV.qmd
      - Publications.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

