---
title: "CV"
editor: visual
---

+-----+-----------------------------------+-----+--------------------------------------+-----+---------------------+-----+--------------------+----+
|     |                                   |     |                                      |     |                     |     |                    |    |
+-----+-----------------------------------+-----+--------------------------------------+-----+---------------------+-----+--------------------+----+
|     | **Mack White Curriculum Vitae**   |     |                                      |     |                     |     |                    |    |
+-----+-----------------------------------+-----+--------------------------------------+-----+---------------------+-----+--------------------+----+
|     |                                   |     |                                      |     |                     |     |                    |    |
+-----+-----------------------------------+-----+--------------------------------------+-----+---------------------+-----+--------------------+----+
|     | **Ph.D. Candidate**               |     | **Florida International University** |     | **mwhite\@fiu.edu** |     | **(304) 482-9142** |    |
+-----+-----------------------------------+-----+--------------------------------------+-----+---------------------+-----+--------------------+----+
|     |                                   |     |                                      |     |                     |     |                    |    |
+-----+-----------------------------------+-----+--------------------------------------+-----+---------------------+-----+--------------------+----+

+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     |                                                                                 |     |         |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     | **EDUCATION**                                                                   |     |         |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     |                                                                                 |     |         |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     | Florida International University - Ph.D., Earth Systems Science (**4.0 GPA**)   |     | Present |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     |                                                                                 |     |         |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     | Tennessee Technological University - M.S., Biology (**4.0 GPA**)                |     | 2021    |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     |                                                                                 |     |         |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     | Marshall University -  B.S., Environmental Science (**3.43 GPA**)               |     | 2017    |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+
|     |                                                                                 |     |         |    |
+-----+---------------------------------------------------------------------------------+-----+---------+----+

+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                         |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **EMPLOYMENT**                                                                                                          |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                         |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **Graduate Research Assistant**  - Florida International University, *Miami, FL* (Advisor: Dr. Jennifer Rehage)         |     | 2021-Present |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                         |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **Graduate Teaching Assistant**  - Tennessee Technological University, *Cookeville, TN* (Advisor: Dr. Kit Wheeler)      |     | 2019-2021    |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                         |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **Contractual Biologist** - Ohio River Valley Water Sanitation Commission (ORSANCO), *Cincinnati, OH*                   |     | 2018         |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                         |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **Watershed Restoration Technician –** Trout Unlimited & United States Forest Service, *Bartow, WV*                     |     | 2017         |    |
|     |                                                                                                                         |     |              |    |
|     |                                                                                                                         |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                         |     |              |    |
+-----+-------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+

+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | **PUBLICATIONS**                                                                                                                                                                                                                                               |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | **White M**, NP Lemoine, JE Allgeier… (17 additional authors; **in prep**) Species richness and functional diversity drives consumer-driven nutrient cycling via asynchronous communities. t*argeting Nature Ecology & Evolution.*                             |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Santos RO, **M White,** WR James, NM Viadero, JA Massie, RE Boucek, and JS Rehage (**in review).** Cause and consequences of individual variability in space use in subtropical riverscapes. *Scientific Reports*.                                             |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Sturges J, WR James, R Rezek, RO Santos, **M White**, G Badlowski, S Trabelsi, JA Massie, J Nelson, J Trexler, and JS Rehage (**in review**). Seasonality drives green and brown energy pathways in food webs across an ecosystem gradient. *Ecosphere*.       |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Hudson RR, K Wheeler, **M White**, and JN Murdock (**2024**). Migratory redhorse suckers provide subsidies of nitrogen but not phosphorus to a spawning stream. *Ecology of Freshwater Fish.*                                                                  |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | **White M,** K Wheeler, RR Hudson, and JN Murdock (**2023**). Salmon of the Southeastern U.S.: Sucker migrations deliver resource subsidies to oligotrophic stream. *Ecology of Freshwater Fish.*                                                              |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Hanscom, R. J.,  **M. White**, C. Cranwell, and M. Grisnik (**2023**). *Regina Septemvittata* (Queen Snake). Geographic distribution. *Herpetological Review* 54 (1):76.                                                                                       |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | **White M** (**2021**). Nutrient contributions from and early life history variability of an adfluvial sucker in an oligotrophic southeastern stream. M.S. Thesis. Available from *ProQuest*.                                                                  |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                                                                                                                |    |
+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+

+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | **FUNDING (\$87,050 total funding)**                                                                                                                        |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Supplemental Research Grant; Funded by NSF CREST Center for Aquatic Chemistry & Env. **(\$4,550**)                                                          |     | 2023 |    |
|     |                                                                                                                                                             |     |      |    |
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Student Travel Grant; Funded by Florida Chapter of American Fisheries Society (**\$300**)                                                                   |     | 2023 |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | NSF Long-Term Ecological Research Synthesis Grant – Principal Investigator; Funded by US-LTER **(\$55,000**)                                                |     | 2022 |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Student Travel Grant; Funded by US-LTER **(\$1,000**)                                                                                                       |     | 2022 |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | FIU ForEverglades Scholarship – Principal Investigator; Funded by Everglades Foundation **(\$25,000**)                                                      |     | 2022 |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Student Travel Grant; Funded by Florida Chapter of American Fisheries Society (**\$300**)                                                                   |     | 2022 |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Colin Cone Writing Scholarship; Funded by Florida Outdoor Writers Association **(\$1,000**)                                                                 |     | 2021 |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                             |     |      |    |
+-----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+

+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | ***Proposals pending or not selected for funding***                                                                          |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Florida Forage Fish Research Fellowship; FFFC & FWRI **(\$15,000**)                                                          |     | 2024 |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Ford Foundation Predoctoral Fellowship; Ford Foundation **(\$30,000**)                                                       |     | 2022 |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Conservation Research Grant; North American Native Fishes Association (**\$1,000**)                                          |     | 2020 |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+

+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | **AWARDS & HONORS**                                                                                                          |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Student of the Year, *Florida Coastal Everglades LTER*                                                                       |     | 2023 |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Best Student Poster Award***,** Florida Coastal Everglades LTER All-Scientists Meeting*                                      |     | 2023 |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Best Student Oral Presentation Award, *Southeastern Fishes Council Meeting*                                                  |     | 2021 |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Best Student Poster Presentation Award, *Southeastern Fishes Council Meeting*                                                |     | 2019 |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                              |     |      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------+-----+------+----+

+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **MENTOR & TEACHING EXPERIENCE**                                                                                                                                                                                                                                       |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | ***Mentoring***                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **Graduate & Undergraduate Student Research Mentor**: MS students - Florida International University (5); UG Students - Florida International University (12), Tennessee Technological University (4); NSF-REU Students – Florida International University (2)         |     | 2019-Present |    |
|     |                                                                                                                                                                                                                                                                        |     |              |    |
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | ***Teaching***                                                                                                                                                                                                                                                         |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **Principles of Ecology Lab (BIOL 3130):** 3 Semesters **-** Tennessee Technological University                                                                                                                                                                        |     | 2020-2021    |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **Principles of Biology Lab (BIOL 1113):** 2 Semesters - Florida International University                                                                                                                                                                              |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                                                                                                                                                                        |     |              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+----+

+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | **UNIVERSITY & PROFESSIONAL SERVICE**                                                                          |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | Aquatic Technical Working Group Committee, *National Ecological Observatory Network*                           |     | 2023-Present |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | Justice, Equity, Diversity, and Inclusion Committee, *Florida Coastal Everglades LTER*                         |     | 2022-Present |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | Justice, Equity, Diversity, and Inclusion Committee, *Southeastern Fishes Council*                             |     | 2021-Present |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | Florida AFS Reefs to Rivers Blog, Editor, *Florida Chapter of the American Fisheries Society*                  |     | 2022-2023    |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | Florida AFS Student Subunit, University Liaison, *Florida Chapter of the American Fisheries Society*           |     | 2022-2023    |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | FCE-LTER Student Subunit, Secretary, *Florida Coastal Everglades LTER*                                         |     | 2021-2022    |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | Biology Graduate Student Society, President, *Biology Department of Tennessee Technological University*        |     | 2020-2021    |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | City of Cookeville Fishing Derby, Event Coordinator, *Tennessee Chapter of the American Fisheries Society*     |     | 2020         |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     | Biology Graduate Student Society, Treasurer, *Biology Department of Tennessee Technological University*        |     | 2019         |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+
|     |                                                                                                                |     |              |    |
+-----+----------------------------------------------------------------------------------------------------------------+-----+--------------+----+

+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | **SELECTED PRESENTATIONS**                                                                                                                                                                             |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Species richness and functional diversity drives nutrient supply stability across marine ecosystems; *Florida Coastal Everglades LTER All-Scientist meeting – poster presentation*                     |     | 2024 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Species richness and functional diversity drives nutrient supply stability across marine ecosystems; *Florida American Fisheries Society annual meeting – poster presentation*                         |     | 2024 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Consumer nutrient dynamics in coastal ecosystem in the wake of global change; *Florida American Fisheries Society annual meeting – poster presentation*                                                |     | 2023 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Consumer nutrient dynamics in coastal ecosystem in the wake of global change; *NSF CREST Center for Aquatic Chemistry & Env. All-Scientists Meeting – poster presentation*                             |     | 2023 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | When world’s collide: Consumer nutrient dynamics in the coastal Everglades; *Florida Coastal Everglades LTER All-Scientists meeting – poster presentation*                                             |     | 2023 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | When world’s collide: Multi-directional movements of fishes and their ecological importance; *Florida American Fisheries Society annual meeting – poster*                                              |     | 2022 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | South Florida Coastal fisheries acoustic telemetry project update; *Florida Atlantic Coast Telemetry Meeting – oral presentation*                                                                      |     | 2021 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Consumer functional roles and the biodiversity of freshwater fishes in the southeast; *Florida International University Department of Earth & Science Seminar Series – oral presentation*              |     | 2021 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Salmon of the South: Suckers in Citico Creek; *Southeastern Fishes Council annual meeting – oral presentation*                                                                                         |     | 2021 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Salmon of the south: Nutrient contributions of an adfluvial catostomid; *Tennessee Technological University Seminar Series – oral presentation*                                                        |     | 2021 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Growth of Rainbow Trout (*Oncorhynchus mykiss*) in Two Tennessee Tailwaters; *Tennessee Chapter of the American Fisheries Society annual meeting – oral presentation*                                  |     | 2021 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Suckers - salmon of the south? *Tennessee Rare Fishes Meeting – oral presentation*                                                                                                                     |     | 2020 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Abundance estimates of spawning catostomids in a small, oligotrophic stream using aerial imagery; *Southeastern Fishes Council annual meeting – oral presentation*                                     |     | 2019 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     | Native brook trout conservation genetics; *Tennessee Technological University Department of Biology Seminar Series – oral presentation*                                                                |     | 2019 |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+
|     |                                                                                                                                                                                                        |     |      |    |
+-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+------+----+

+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | **SPECIALIZED SKILLS**                                                                                                                                                       |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Proficiency in R, Git, GitHub, QGIS, and ArcGIS                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Extensive backcountry, kayak, canoe, trailering, and boating experience                                                                                                      |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Extensive electrofishing (backpack-, barge-, and boat-), seining, and snorkeling experience                                                                                  |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Extensive acoustic, passive integrated transponder, and coded wired tagging experience                                                                                       |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Extensive fish identification, water quality analysis (discrete auto-analyzer and handheld fluorometry), macroinvertebrate identification, and DNA extraction experience     |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     | Extensive experience troubleshooting electrical and mechanical issues in the field (e.g., electrofishing equipment, boat motors, etc.)                                       |    |
|     |                                                                                                                                                                              |    |
|     |                                                                                                                                                                              |    |
|     |                                                                                                                                                                              |    |
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
|     |                                                                                                                                                                              |    |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+
